source 'https://github.com/CocoaPods/Specs.git'
#use_frameworks!

platform :ios, '7.0'

target 'MXPagerView_Example' do
  pod "MXPagerView", :path => "../"
end

target 'MXPagerView_Tests' do
  pod "MXPagerView", :path => "../"
end
