source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'MXPagerView_Example', :exclusive => true do
  pod "MXPagerView", :path => "../"
end

target 'MXPagerView_Tests', :exclusive => true do
  pod "MXPagerView", :path => "../"

  
end
